name: karma_palace
description: Shithead Card Game
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.4.3+1
  json_annotation: ^4.9.0
  flutter_staggered_grid_view: ^0.7.0
  json_serializable: ^6.8.0
  retrofit: ^4.1.0
  share_plus: ^9.0.0
  uuid: ^3.0.7
  logger: ^2.4.0
  firebase_core: ^2.31.0
  firebase_crashlytics: ^3.5.5  # Error reporting
  firebase_database: ^10.5.5
  audioplayers: ^6.0.0
  go_router: ^6.0.1
  logging: ^1.1.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  games_services: ^3.0.1  # Achievements and leaderboards
  google_mobile_ads: ^2.0.1  # Ads
  in_app_purchase: ^3.0.1  # In-app purchases

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  retrofit_generator: ^8.1.0
  flutter_launcher_icons: ^0.13.1
  test: ^1.19.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/music/
    - assets/sfx/

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/Permanent_Marker/PermanentMarker-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon-adaptive-foreground.png"
